---
- hosts: all
  become: yes
  tasks:
    - name: Actualizaciones
      apt: update_cache=yes

    - name: Instalar git
      apt: name=git state=present

    - name: Instalar Python python3
      apt: name=python3 state=present

    - name: Installing pip3
      apt: name=python3-pip state=present

    - name: Toca clinar el proyecto
      git:
        repo: https://github.com/xenahort/proyectoCloudComputing
        dest: "~/proyectoCloudComputing"

    - name: Instalar fichero requirements 
      shell: "pip3 install -r ~/proyectoCloudComputing/requirements.txt"