---
- hosts: all
  become: yes
  vars:
    project_path: ~/proyectoCloudComputing
  tasks:
    - name: Actualizaciones
      apt: update_cache=yes

    - name: Instalar git
      apt: name=git state=present

    - name: Instalar Python python3
      apt: name=python3 state=present